version: "3.8"
services:
  lm-solutions-nextjs:
    image: lmaslovs/lm-solutions:latest
    expose:
      - "3000" # Expose the internal port
    networks:
      - lm-solutions-network

  lm-solutions-nginx:
    image: nginx:latest
    ports:
      - "81:80" # Use port 81 for HTTP to avoid conflict with other services on port 80
    environment:
      - SERVER_NAME=${SERVER_NAME}
    command: /bin/bash -c "envsubst '$$SERVER_NAME' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    volumes:
      - ./lm-solutions-nginx.conf.template:/etc/nginx/nginx.conf.template:ro
    depends_on:
      - lm-solutions-nextjs
    networks:
      - lm-solutions-network

networks:
  lm-solutions-network:
    driver: bridge
