version: "3.8"
services:
  lm-solutions-nextjs:
    image: lmaslovs/lm-solutions:latest
    expose:
      - "3000"
    networks:
      - lm-solutions-network

  lm-solutions-nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVER_NAME=${SERVER_NAME}
    command: /bin/bash -c "envsubst '$$SERVER_NAME' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - lm-solutions-nextjs
    networks:
      - lm-solutions-network

networks:
  lm-solutions-network:
    driver: bridge
